require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PreworkModulesController do

  # This should return the minimal set of attributes required to create a valid
  # PreworkModule. As you add validations to PreworkModule, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "order" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PreworkModulesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all prework_modules as @prework_modules" do
      prework_module = PreworkModule.create! valid_attributes
      get :index, {}, valid_session
      assigns(:prework_modules).should eq([prework_module])
    end
  end

  describe "GET show" do
    it "assigns the requested prework_module as @prework_module" do
      prework_module = PreworkModule.create! valid_attributes
      get :show, {:id => prework_module.to_param}, valid_session
      assigns(:prework_module).should eq(prework_module)
    end
  end

  describe "GET new" do
    it "assigns a new prework_module as @prework_module" do
      get :new, {}, valid_session
      assigns(:prework_module).should be_a_new(PreworkModule)
    end
  end

  describe "GET edit" do
    it "assigns the requested prework_module as @prework_module" do
      prework_module = PreworkModule.create! valid_attributes
      get :edit, {:id => prework_module.to_param}, valid_session
      assigns(:prework_module).should eq(prework_module)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PreworkModule" do
        expect {
          post :create, {:prework_module => valid_attributes}, valid_session
        }.to change(PreworkModule, :count).by(1)
      end

      it "assigns a newly created prework_module as @prework_module" do
        post :create, {:prework_module => valid_attributes}, valid_session
        assigns(:prework_module).should be_a(PreworkModule)
        assigns(:prework_module).should be_persisted
      end

      it "redirects to the created prework_module" do
        post :create, {:prework_module => valid_attributes}, valid_session
        response.should redirect_to(PreworkModule.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved prework_module as @prework_module" do
        # Trigger the behavior that occurs when invalid params are submitted
        PreworkModule.any_instance.stub(:save).and_return(false)
        post :create, {:prework_module => { "order" => "invalid value" }}, valid_session
        assigns(:prework_module).should be_a_new(PreworkModule)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PreworkModule.any_instance.stub(:save).and_return(false)
        post :create, {:prework_module => { "order" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested prework_module" do
        prework_module = PreworkModule.create! valid_attributes
        # Assuming there are no other prework_modules in the database, this
        # specifies that the PreworkModule created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PreworkModule.any_instance.should_receive(:update_attributes).with({ "order" => "1" })
        put :update, {:id => prework_module.to_param, :prework_module => { "order" => "1" }}, valid_session
      end

      it "assigns the requested prework_module as @prework_module" do
        prework_module = PreworkModule.create! valid_attributes
        put :update, {:id => prework_module.to_param, :prework_module => valid_attributes}, valid_session
        assigns(:prework_module).should eq(prework_module)
      end

      it "redirects to the prework_module" do
        prework_module = PreworkModule.create! valid_attributes
        put :update, {:id => prework_module.to_param, :prework_module => valid_attributes}, valid_session
        response.should redirect_to(prework_module)
      end
    end

    describe "with invalid params" do
      it "assigns the prework_module as @prework_module" do
        prework_module = PreworkModule.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PreworkModule.any_instance.stub(:save).and_return(false)
        put :update, {:id => prework_module.to_param, :prework_module => { "order" => "invalid value" }}, valid_session
        assigns(:prework_module).should eq(prework_module)
      end

      it "re-renders the 'edit' template" do
        prework_module = PreworkModule.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PreworkModule.any_instance.stub(:save).and_return(false)
        put :update, {:id => prework_module.to_param, :prework_module => { "order" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested prework_module" do
      prework_module = PreworkModule.create! valid_attributes
      expect {
        delete :destroy, {:id => prework_module.to_param}, valid_session
      }.to change(PreworkModule, :count).by(-1)
    end

    it "redirects to the prework_modules list" do
      prework_module = PreworkModule.create! valid_attributes
      delete :destroy, {:id => prework_module.to_param}, valid_session
      response.should redirect_to(prework_modules_url)
    end
  end

end
